### ISSUE TITLE
Fix updates from the future

### ISSUE THREAD

**Issue by zidhuss** [scinos/scinos-blog-11ty#46]
Hey time traveler! Stumbled upon your blog and saw your updates from 1 year in the future:

https://github.com/scinos/scinos-blog-11ty/blob/9e2e417fac621864552832695132fcbfb1a6e3b1/src/posts/2023-07-30-bun-vs-yarn-a-comparison-of-package-installation.md?plain=1#L171-L199

**Comment by scinos** [comment]
Thanks!!
